package com.dokar.anav.compiler;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class Utils {

    public static final String GEN_CODE_COMMENT = "Generated by anav";

    public static final String TYPE_ACTIVITY = "android.app.Activity";
    public static final String TYPE_INTENT = "android.content.Intent";

    public static final Map<String, String> INTENT_EXTRA_GETTERS =
            new HashMap<String, String>() {
                {
                    put("byte", "getByteExtra($N, 0)");
                    put("byte[]", "getByteArrayExtra($N)");

                    put("short", "getShortExtra($N, 0)");
                    put("short[]", "getShortArrayExtra($N)");

                    put("char", "getCharExtra($N, 0)");
                    put("char[]", "getCharArrayExtra($N)");

                    put("boolean", "getBooleanExtra($N, false)");
                    put("boolean[]", "getBooleanArrayExtra($N)");

                    put("int", "getIntExtra($N, 0)");
                    put("int[]", "getIntArrayExtra($N)");

                    put("long", "getLongExtra($N, 0L)");
                    put("long[]", "getLongArrayExtra($N)");

                    put("float", "getFloatExtra($N, 0f)");
                    put("float[]", "getFloatArrayExtra($N)");

                    put("double", "getDoubleExtra($N, 0.0)");
                    put("double[]", "getDoubleArrayExtra($N)");

                    put("java.lang.String", "getStringExtra($N)");
                    put("java.lang.String[]", "getStringArrayExtra($N)");

                    put("java.lang.CharSequence", "getCharSequenceExtra($N)");
                    put("java.lang.CharSequence[]", "getCharSequenceArrayExtra($N)");

                    put("java.io.Serializable", "getSerializableExtra($N)");

                    put("android.os.Bundle", "getBundleExtra($N)");

                    put("android.os.Parcelable", "getParcelableExtra($N)");
                    put("android.os.Parcelable[]", "getParcelableArrayExtra($N)");
                }
            };

    public static String capitalize(@NotNull String word) {
        return word.substring(0, 1).toUpperCase() +
                word.substring(1);
    }

    /**
     * toUpperCase for variable name, transformations will like this:
     * user -> USER
     * userId -> USER_ID
     */
    public static String variableUpperCase(@NotNull String text) {
        StringBuilder builder = new StringBuilder();

        boolean lower = false;
        int prev = 0;
        char[] chars = text.toCharArray();

        for (int i = 0; i < chars.length; i++) {
            if (lower && chars[i] >= 'A' && chars[i] <= 'Z') {
                builder.append(chars, prev, i - prev);
                builder.append('_');
                lower = false;
                prev = i;
            } else {
                lower = true;
            }
        }

        builder.append(chars, prev, chars.length - prev);

        return builder.toString().toUpperCase();
    }

    /**
     * Get package name and class simple name from class's getCanonicalName().
     *
     * @param classCanonicalName name from class.getCanonicalName()
     * @return String array: [packageName, classSimpleName]
     * <p>
     * Example:
     * "java.lang.String" -> ["java.lang", "String"]
     * </p>
     */
    @NotNull
    public static String[] getPackageAndClassSimpleName(
            @NotNull String classCanonicalName) {
        int lastDot = classCanonicalName.lastIndexOf('.');
        if (lastDot == -1) {
            return new String[]{"", classCanonicalName};
        } else {
            return new String[]{
                    classCanonicalName.substring(0, lastDot),
                    classCanonicalName.substring(lastDot + 1)
            };
        }
    }

    public static String removeActivitySuffix(String text) {
        return removeSuffix(text, "Activity");
    }

    public static String removeSuffix(String text, String suffix) {
        if (text == null || suffix == null || !text.endsWith(suffix)) {
            return text;
        }
        return text.substring(0, text.length() - suffix.length());
    }

    @Nullable
    public static String textFromFile(File file) {
        if (file == null || !file.exists()) {
            return null;
        }

        try {
            Path path = Paths.get(file.getAbsolutePath());
            return Files.lines(path).collect(Collectors.joining());
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }

    public static boolean writeText(File file, String text) {
        if (!file.exists()) {
            try {
                if (!file.getParentFile().exists()) {
                    if (!file.getParentFile().mkdirs()) {
                        System.out.println("Cannot mkdirs for file: \n" +
                                file.getAbsolutePath());
                        return false;
                    }
                }

                if (!file.createNewFile()) {
                    System.out.println("Cannot create file: \n" +
                            file.getAbsolutePath());
                    return false;
                }
            } catch (IOException e) {
                e.printStackTrace();
                return false;
            }
        }

        Path path = Paths.get(file.getAbsolutePath());

        try (BufferedWriter writer =
                     Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            writer.write(text);
            return true;
        } catch (IOException e) {
            e.printStackTrace();
        }

        return false;
    }
}
