// Generated by anav
package com.dokar.anav.mmsample.base.navigation

import android.content.Intent
import kotlin.Int
import kotlin.String
import kotlin.Suppress

@Suppress("RedundantVisibilityModifier")
public object NavArgs {
    public object Account {
        public const val USERNAME: String = "com.dokar.anav.mmsample.home.extra.USERNAME"

        public const val USER_ID: String = "com.dokar.anav.mmsample.home.extra.USER_ID"

        public var Intent.username: String?
            get() = getStringExtra(USERNAME)
            set(value) {
                putExtra(USERNAME, value)
            }

        public var Intent.userId: Int?
            get() = getIntExtra(USER_ID, 0)
            set(value) {
                putExtra(USER_ID, value)
            }
    }

    public object Settings {
        public const val TWITTER: String = "com.dokar.anav.mmsample.settings.extra.TWITTER"

        public const val NAME: String = "com.dokar.anav.mmsample.settings.extra.NAME"

        public const val AVATAR: String = "com.dokar.anav.mmsample.settings.extra.AVATAR"

        public const val AGE: String = "com.dokar.anav.mmsample.settings.extra.AGE"

        public var Intent.twitter: String?
            get() = getStringExtra(TWITTER)
            set(value) {
                putExtra(TWITTER, value)
            }

        public var Intent.name: String?
            get() = getStringExtra(NAME)
            set(value) {
                putExtra(NAME, value)
            }

        public var Intent.avatar: String?
            get() = getStringExtra(AVATAR)
            set(value) {
                putExtra(AVATAR, value)
            }

        public var Intent.age: String?
            get() = getStringExtra(AGE)
            set(value) {
                putExtra(AGE, value)
            }
    }
}
