// Generated by anav
package com.dokar.anav.mmsample.base.navigation

import kotlin.String
import kotlin.Suppress

@Suppress("RedundantVisibilityModifier")
public object NavMap {
    public const val About: String = "com.dokar.anav.mmsample.about.AboutActivity"

    public const val Settings: String = "com.dokar.anav.mmsample.settings.SettingsActivity"

    public object Home {
        public const val Account: String = "com.dokar.anav.mmsample.home.AccountActivity"

        public const val Home: String = "com.dokar.anav.mmsample.home.HomeActivity"
    }
}
